### ISSUE TITLE
Parsing error in firecracker CNI config 

### ISSUE THREAD

**Issue by sravan-s** [k-jingyang/k-jingyang.github.io#15]
First of all, thanks for the blog, it was quite useful for some of my experiments with firecracker

https://github.com/k-jingyang/k-jingyang.github.io/blob/master/_posts/2024-06-15-firecracker-bridge.md?plain=1#L66
`"subnet": "172.16.0.0/24",`
That trailing comma cause error in parsing the config.

**Comment by k-jingyang** [comment]
@sravan-s, glad my posts helped! Thanks for letting me know. 

Curious, what are you trying out with firecracker?

**Comment by sravan-s** [comment]
I was trying to build something like back-end for a coding notebook(similar to jupyter, zeppelin etc.) 

A notebook is made of pargraphs, each paragraph is a block of code .
Each notebook gets a firecracker VM
I design some APIs to share data between paragraphs ~

**Comment by k-jingyang** [comment]
That's cool!
